name: Deployment Request
description: Submit a deployment/change request
title: "[DEPLOYMENT] "
labels:
  - new-request

body:
  - type: markdown
    attributes:
      value: |
        ## Change Information

  - type: input
    id: application_name
    attributes:
      label: Application Name
      options: 
       - "Pennant"
       - "SFDC"
       - "LCS"
       - "Jayam LMS"
       - "Sales Central"
       - "Credit Central"
       - "OPS Central"
       - "Inbound Payment Service"
       - "Policy Engine"
       - "LMS-Loan Management System(API)"
       - "Disbursement Service"
       - "Repayment Service"
       - "CrisMac"
       - "SnowFlake"
       - "CAT: Compliance Automation Tool"
       - "Securitization"
       - "Partner Central"
       - "KYC Service"
       - "Miles LMS"
       - "Data Central"
       - "DMS"
       - "Trackwizz AML"
       - "Algo-Fushion"
       - "DTM"
       - "JupyterHub"
       - "Document Management Service(Kanaja)"
       - "Event based Loading(Lambda)"
       - "AWS Sagemaker"
       - "Glue"
       - "Talend"
       - "IMS"
       - "Finance Central"
       - "TechOps"
       - "RPA"
       - "RBAC System"
       - "NACH Platform"
       - "Mudra Stack(Embedded Finance)"
       - "LVS- Legal Verification System"
       - "Customer Account Services"
       - "D2C Shakthi"
       - "RCAL"
       - "PowerBI"
       - "Disprz"
       - "Darwinbox"
       - "HR Tech"
       - "Nginx"
       - "Cogno.ai(Whatsapp bots)"
       - "Qualtrics(Surveys)"
       - "M2P"
       - "SAMPARK"
       - "Cost per file"
       - "HSA"
       - "Sharepoint"
       - "CLM"
       - "Fraud Central"
       - "Possidex"
       - "COC"
       - "DevOps"
       - "Fraud Investigation"
       - "Microsure- MFI"
       - "Oracle Fusion"
       - "SAP TRM"
    validations:
      required: true

  - type: dropdown
    id: change_category
    attributes:
      label: Change Category
      options:
        - "Standard"
        - "Emergency"
        - "Minor"
        - "Major"
    validations:
      required: true

  - type: input
    id: cmstp_team
    attributes:
      label: CMSTP for Team
      options: 
        - "Internal Engineering"
        - "Business Solution Group(BSG)"
        - "APIGEE"
        - "Securitization"
        - "Network"
        - "DPE"
        - "Partner Function- Finance"
        - "Partner Function- Treasury"
        - "Partner Function- Other Functions"
    validations:
      required: true

  - type: input
    id: cmstp_execution_owner
    attributes:
      label: CMSTP Execution Owner
      options:
        - "PRF DevOps"
        - "Business Solution Group(BSG)"
        - "APIGEE"
        - "Securitization"
        - "Network"
        - "DPE"
        - "Partner Function- Finance"
        - "Partner Function- Treasury"
        - "Partner Function- Other Functions"
    validations:
      required: true


  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      options:
        - "Enhancement"
        - "New Feature"
        - "Infra Change"
        - "DevOps Tool Upgrade"
        - "Production Bug Fix"
        - "Mongo DB Script"
        - "Postgres Script"
        - "AWS Paramstore Updates"
        - "Cron Execution"
        - "Tech Debt"
        - "Config"
        - "External/Partner/3P/2P Service Onboarding on Nginx"
        - "FCS flags"
        - "Mongo DB changes for feature Rollout"
        - "Postgres changes for feature Rollout"
        - "Policy updates in Policy Engine service"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "Low"
        - "High"
        - "Critical"
    validations:
      required: true


  - type: textarea
    id: change_description
    attributes:
      label: Change Description
      description: Add a Description(Required)
    validations:
      required: true

  - type: input
    id: components
    attributes:
      label: Components
      options:
       - "techdebt"

  - type: input
    id: labels_value
    attributes:
      label: Labels
      options:
        - "Policy Engine"
        - "None"
        - "PL_DOCUMENT_PAGE"
        - "Validations"
        - "advanceemi"
        - "PD-777"
        - "MODULE_ADMIN_FCU"
        - "application:fraud-service"
        - "CCUBL2024Sprint5Removal"
        - "coc-oe"
        - "plat-release-FY26-Q2-Sprint5-Week2"
        - "PL_CAM_PAGE"
        - "LADS-NI"
        - "uri:/v1/check/applicant"
        - "CC_QA"
        - "SPRUTI_TESTCASE_NOTEXECUTED_BY_DEV"
        - "CrxUBLQ12024"
        - "name:APPLICANT_SEARCH_CIRCUIT_BREAKER"
        - "TShirtSize_M"
        - "SX_Insurance_Bug"

  - type: markdown
    attributes:
      value: |
        ## Schedule

  - type: input
    id: planned_start
    attributes:
      label: Planned Start Time
      placeholder: 26-Aug-2026 10:00 PM IST
    validations:
      required: true

  - type: input
    id: planned_end
    attributes:
      label: Planned End Time
      placeholder: 26-Aug-2026 11:00 PM IST
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Stakeholders & Notifications

  - type: input
    id: product_manager
    attributes:
      label: Notification to Product Manager
      placeholder: GitHub Username
    validations:
      required: true

  - type: input
    id: business_user
    attributes:
      label: Notification to Business User
      placeholder: GitHub Username
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Source Control Information

  - type: input
    id: compare_from
    attributes:
      label: Compare From
      description: Previous Release Tag / Branch / Commit
      placeholder: v1.2.3
    validations:
      required: true

  - type: input
    id: compare_to
    attributes:
      label: Compare To
      description: New Release Tag / Branch / Commit
      placeholder: v1.2.4
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Impact Assessment

  - type: input
    id: branches_impacted
    attributes:
      label: No of Branches Impacted
      options: 
        - "Zero"
        - "One"
        - "More than One"
        - "All"

  - type: input
    id: ef_partners_impacted
    attributes:
      label: No of EF Partners Impacted
      options: 
        - "Zero"
        - "One"
        - "More than One"
        - "All"

  - type: input
    id: tech_products_impacted
    attributes:
      label: No of Tech Products Impacted
      options: 
        - "Zero"
        - "One"
        - "More than One"
        - "All"

  - type: input
    id: loan_products_impacted
    attributes:
      label: No of Loan Products Impacted
      options: 
        - "Zero"
        - "One"
        - "More than One"
        - "All"

  - type: textarea
    id: dependencies
    attributes:
      label: List of dependencies for this change to successfully work on production
    validations:
      required: true

  - type: textarea
    id: dependent_modules
    attributes:
      label: List of modules (services, functionalities, clients) on production that are dependent on the components being changed
    validations:
      required: true

  - type: textarea
    id: collection_backup
    attributes:
      label: Is collection backup required, for the script execution
    validations:
      required: true


  - type: textarea
    id: services_at_risk
    attributes:
      label: List of things working on production that are at risk of breaking because of this change
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Testing & QA Validation

  - type: dropdown
    id: qa_test_report_required
    attributes:
      label: QA - Test Report?
      options:
        - "Yes"
        - "Not Required"
    validations:
      required: true

  - type: input
    id: qa_test_report
    attributes:
      label: QA Test Report
    validations:
      required: true  

  - type: textarea
    id: testing_details
    attributes:
      label: Areas identified for testing and Regression
    validations:
      required: true

  - type: textarea
    id: testing_exceptions
    attributes:
      label: Are we bypassing any failure from testing?
    validations:
      required: true

  - type: textarea
    id: stage_validated
    attributes:
      label: Has the change been deployed and tested in STAGE environment
    validations:
      required: true

  - type: dropdown
    id: em_checked_code_diff
    attributes:
      label: Has EM checked the code diff? is it part of Release note?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: qa_reviewed_design
    attributes:
      label: Has QA team seen the design document and understood all the associated integrations?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: em_reviewed_test_report
    attributes:
      label: Has EM seen/reviewed the test report?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: qa_tested_integrations
    attributes:
      label: Has QA tested all integrations? Answer NA wherever not applicable
      options:
        - "Yes"
        - "No"
        - "NA"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Controlled Launch Plan

  - type: dropdown
    id: canary_deployment
    attributes:
      label: Canary Deployment
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: canary_deployment_details
    attributes:
      label: Canary Deployment Details (The canary should be started with 1% traffic weight, 1 branch, partner)
    validations:
      required: true
  
  - type: textarea
    id: test_report
    attributes:
      label: Test Report for breaking changes ( discuss with the dependent EM, in case of any query)?
    validations:
      required: true


  - type: dropdown
    id: nginx_gateway_required
    attributes:
      label: Nginx API Gateway deployment required for Internal microservice?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: nginx_caller_service
    attributes:
      label: Specify the Caller App/Service name(s) if Nginx deployment is selected "Yes"

  - type: dropdown
    id: controlled_launch
    attributes:
      label: Controlled Launch Plan
      options:
        - "Yes"
        - "No"
    validations:
      required: true



  - type: textarea
    id: launch_plan_details
    attributes:
      label: Launch Plan Details
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Configuration Changes

  - type: dropdown
    id: aws_config_change
    attributes:
      label: AWS Config Changes
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: config_version
    attributes:
      label: Config Version
      placeholder: v1.0
    validations:
      required: true

  - type: textarea
    id: application_configurations
    attributes:
      label: Application Configurations(Node EWS, AWS Paramstore)
      options: 
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: configuration_details
    attributes:
      label: Application Configurations Details
    validations:
      required: true

  - type: input
    id: apigee_reference_url
    attributes:
      label: Apigee reference to onboard URL
      placeholder: https://...

  - type: markdown
    attributes:
      value: |
        ## Deployment Execution

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan
    validations:
      required: true
  
  - type: textarea
    id: post_implementation
    attributes:
      label: Post Implementation Monitoring Plan
    validations:
      required: true

  - type: textarea
    id: monitoring_plan
    attributes:
      label: List of functional metrics to monitor and details of what needs to be monitored (what values of metrics will tell us working fine VS some issues)
    validations:
      required: true

  - type: textarea
    id: rollback_plan
    attributes:
      label: Rollback Plan
    validations:
      required: true
  
  - type: input
    id: assignee_id
    attributes:
      label: Assignee
      placeholder: GitHub Username
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        ## Approval Chain

  - type: input
    id: level1_ux_qa
    attributes:
      label: Level-1 UX Design QA [After fixing all the UX Blockers]
      placeholder: GitHub Username
    validations:
      required: true

  - type: input
    id: level2_architecture
    attributes:
      label: Level-2 Architecture [To be approved by SDE3+]
      placeholder: GitHub Username
    validations:
      required: true

  - type: input
    id: level3_infosec
    attributes:
      label: Level-3 Infosec Lead
      placeholder: GitHub Username
    validations:
      required: true

  - type: input
    id: level4_manager
    attributes:
      label: Level-4 Manager
      placeholder: GitHub Username
    validations:
      required: true

  - type: input
    id: level5_qa
    attributes:
      label: Level-5 QA
      placeholder: GitHub Username
    validations:
      required: true

  - type: input
    id: level6_doe
    attributes:
      label: Level-6 DoE
      placeholder: GitHub Username
    validations:
      required: true
    
    
